#TODO: Fikse NAIS.yaml
#TODO: Endre accessPolicy
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: oebs-omada-api-u1
  namespace: team-oebs
  labels:
    app: oebs-omada-api-u1
    team: team-oebs

spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1

  resources:
    requests:
      cpu: 400m
      memory: 1024Mi
    limits:
      cpu: 4000m
      memory: 2048Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
  envFrom:
    - secret: oebs-omada-u1

  prometheus:
    enabled: true
    path: /actuator/prometheus

  ingresses:
     - "https://oebs-omada-api-u1.intern.dev.nav.no"
