#TODO: Fikse NAIS.yaml
#TODO: Endre accessPolicy
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: oebs-omada-api-q1
  namespace: team-oebs
  labels:
    app: oebs-omada-api-q1
    team: team-oebs
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1

  resources:
    requests:
      cpu: 50m
      memory: 400Mi
    limits:
      memory: 500Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
  envFrom:
    - secret: oebs-omada-q1

  prometheus:
    enabled: true
    path: /actuator/prometheus

  ingresses:
    - "https://oebs-omada-api-q1.intern.dev.nav.no"