#TODO: Fikse NAIS.yaml
#TODO: Endre accessPolicy
apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: oebs-omada-api
  namespace: team-oebs
  labels:
    app: oebs-omada-api
    team: team-oebs

spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 3
    max: 3

  resources:
    requests:
      cpu: 400m
      memory: 1024Mi
    limits:
      cpu: 4000m
      memory: 2048Mi

  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
  envFrom:
    - secret: oebs-omada

  prometheus:
    enabled: true
    path: /actuator/prometheus

  ingresses:
    - "https://oebs-omada-api.intern.nav.no"