apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: oebs-omada-api-q1
  namespace: team-oebs
  labels:
    app: oebs-omada-api-q1
    team: team-oebs
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1

  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 1Gi
  env:
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MaxRAMPercentage=60.0 -XX:InitialRAMPercentage=40.0 -XX:MaxMetaspaceSize=200m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heapdump.hprof"
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
  envFrom:
    - secret: oebs-omada-q1

  prometheus:
    enabled: true
    path: /actuator/prometheus

  ingresses:
    - "https://oebs-omada-api-q1.intern.dev.nav.no"