
server:
  port: 8080

no.nav.security.jwt:
   issuer:
     azure:
       accepted_audience: ${AZURE_ACCEPTED_AUDIENCE}
       discovery-url: ${AZURE_DISCOVERY_URL}

spring:
  profiles:
     active: nais
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${APPS_USER}
    password: ${APPS_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
      # database-platform: org.hibernate.dialect.OracleDialect
    show-sql: false
    open-in-view: false
  application:
    name: ${APP_NAME}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics

springdoc:
  packagesToScan: no.nav.oebs.api.controller
  override-with-generic-response: false
  remove-broken-reference-definitions: false
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha

#logging:
  #level:
    #com.zaxxer.hikari: DEBUG
    # root: DEBUG
    # org.springframework.web: debug
    # org.hibernate: error
    # org.springframework: DEBUG
    # no.nav= DEBUG