
server:
  port: 8080

# Application metadata
OEBS_ENV: ${OEBS_ENV:LOCAL}
APP_VERSION: ${APP_VERSION:0.4.6}
APP_UPDATE: ${APP_UPDATE:2026-02-23}
APP_NAME: ${APP_NAME:oebs-omada-api}

#no.nav.security.jwt:
#   issuer:
#     azure:
#       accepted_audience: ${AZURE_ACCEPTED_AUDIENCE}
#       discovery-url: ${AZURE_DISCOVERY_URL}

spring:
  profiles:
     active: nais
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${APPS_USER}
    password: ${APPS_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics

springdoc:
  packagesToScan: no.nav.oebs.api.controller
  override-with-generic-response: false
  remove-broken-reference-definitions: false
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha